In [1]:
import numpy as np

In [2]:
l = [1,2 , 3,4,4]

In [3]:
type(l)

list

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4, 4])

In [7]:
a1 = np.array([[1,2,3],[3,4,5]])

In [8]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [21]:
a2 = np.array([[[1,2,3],[0.3,4,0.5]]])

In [15]:
a2

array([[[1. , 2. , 3. ],
        [0.3, 4. , 0.5]]])

In [11]:
a.ndim

1

In [12]:
a1.ndim

2

In [13]:
a2.ndim

3

In [19]:
a3 = np.array([[[1,2,3],[0.3,4,0.5]],[[1,2,3],[0.3,4,0.5]],[[1,2,3],[0.3,4,0.5]],[[1,2,3],[0.3,4,0.5]]])

In [20]:
a3

array([[[1. , 2. , 3. ],
        [0.3, 4. , 0.5]],

       [[1. , 2. , 3. ],
        [0.3, 4. , 0.5]],

       [[1. , 2. , 3. ],
        [0.3, 4. , 0.5]],

       [[1. , 2. , 3. ],
        [0.3, 4. , 0.5]]])

In [22]:
a3.ndim

3

In [23]:
l = [1,2,3,4]

In [24]:
a = np.asarray(l)

array([1, 2, 3, 4])

In [26]:
m= np.matrix(l)

In [27]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [28]:
np.asanyarray(a)

array([1, 2, 3, 4, 4])

In [29]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [30]:
a

array([1, 2, 3, 4, 4])

In [31]:
a1 = a

In [32]:
a1

array([1, 2, 3, 4, 4])

In [33]:
a

array([1, 2, 3, 4, 4])

In [34]:
a[0]

1

In [35]:
a[0]= 10

In [36]:
a

array([10,  2,  3,  4,  4])

In [38]:
# due assignment
a1

array([10,  2,  3,  4,  4])

In [39]:
a1[3] = 50

In [40]:
a1

array([10,  2,  3, 50,  4])

In [41]:
a

array([10,  2,  3, 50,  4])

In [42]:
a2  = np.copy(a)

In [43]:
a2

array([10,  2,  3, 50,  4])

In [44]:
a2[2] = 30

In [45]:
a2

array([10,  2, 30, 50,  4])

In [46]:
a1

array([10,  2,  3, 50,  4])

In [47]:
a

array([10,  2,  3, 50,  4])

In [49]:
# generate array
np.fromfunction(lambda i,j : i==j ,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [48]:
np.fromfunction(lambda i,j : i==j ,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [50]:
np.random.rand(2,3)

array([[0.76406244, 0.68854558, 0.73994642],
       [0.7906595 , 0.75015259, 0.01913508]])

In [51]:
np.random.rand(2,3,2)

array([[[0.78340662, 0.45905601],
        [0.13057832, 0.80783973],
        [0.67759982, 0.06184429]],

       [[0.58981482, 0.60421385],
        [0.01472733, 0.78706304],
        [0.88491097, 0.44486721]]])

In [52]:
np.random.rand(2,3,2,2)

array([[[[0.27451272, 0.43762298],
         [0.75802574, 0.04882119]],

        [[0.78527018, 0.72962464],
         [0.47752404, 0.08199146]],

        [[0.1456519 , 0.37310257],
         [0.29979531, 0.00393917]]],


       [[[0.8166737 , 0.58755113],
         [0.63192211, 0.66741215]],

        [[0.6614859 , 0.46185137],
         [0.98077041, 0.73740095]],

        [[0.56187894, 0.84641096],
         [0.2659971 , 0.19809467]]]])

In [54]:
np.random.rand(3,4,4)

array([[[0.19519164, 0.97636189, 0.287804  , 0.83424838],
        [0.13380409, 0.19999408, 0.58561941, 0.15708987],
        [0.2565914 , 0.63466581, 0.28720786, 0.29452278],
        [0.53440876, 0.902652  , 0.54457112, 0.26541773]],

       [[0.50158415, 0.58054923, 0.20787754, 0.3463602 ],
        [0.9142929 , 0.65921368, 0.41692511, 0.5168321 ],
        [0.14495448, 0.07520009, 0.44309548, 0.05813578],
        [0.93638359, 0.53524339, 0.16184116, 0.49015495]],

       [[0.19964291, 0.99065411, 0.56855231, 0.03332061],
        [0.28143616, 0.57027707, 0.66940602, 0.93268759],
        [0.58716516, 0.1278521 , 0.73852633, 0.71923731],
        [0.69533032, 0.90519144, 0.14646693, 0.7003639 ]]])

In [61]:
d1= np.random.randint(0,10,(4,2,4))

In [58]:
import pandas as pd

In [56]:
d = np.random.rand(3,4)

In [59]:
df = pd.DataFrame(d)

In [60]:
df

0         1         2         3
0  0.298639  0.902577  0.723655  0.900630
1  0.141952  0.238981  0.386050  0.617647
2  0.475119  0.801164  0.796625  0.247540

In [62]:
d1

array([[[0, 8, 8, 4],
        [6, 0, 3, 7]],

       [[3, 1, 3, 5],
        [2, 2, 1, 1]],

       [[3, 8, 9, 7],
        [6, 7, 3, 4]],

       [[3, 6, 9, 7],
        [8, 2, 5, 1]]])

In [64]:
d1.reshape(8 , 4)

array([[0, 8, 8, 4],
       [6, 0, 3, 7],
       [3, 1, 3, 5],
       [2, 2, 1, 1],
       [3, 8, 9, 7],
       [6, 7, 3, 4],
       [3, 6, 9, 7],
       [8, 2, 5, 1]])

In [67]:
d1 = d1.reshape(8,-1)

In [69]:
# Data frame alway in 2D 
pd.DataFrame(d1)

0  1  2  3
0  0  8  8  4
1  6  0  3  7
2  3  1  3  5
3  2  2  1  1
4  3  8  9  7
5  6  7  3  4
6  3  6  9  7
7  8  2  5  1