In [1]:
import numpy as np

In [4]:
range(10)

range(0, 10)

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [9]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [12]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [13]:
np.arange(5,-4,-0.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [15]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [16]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [19]:
np.logspace(1,4,4,base=2) # LOG 2

array([ 2.,  4.,  8., 16.])

In [20]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((4,5)) *2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [23]:
np.empty((2,3))

array([[4.64361914e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [25]:
np.eye(4) # iddentity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
a = np.eye(4)

In [27]:
a.shape

(4, 4)

In [28]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
a.size

16

In [30]:
a.ndim

2

In [31]:
a1 = np.random.rand(3,4)

In [32]:
a1

array([[0.52063196, 0.13677528, 0.41751416, 0.4949577 ],
       [0.65082356, 0.7564854 , 0.25736709, 0.09710427],
       [0.1417847 , 0.85675989, 0.61461029, 0.82323889]])

In [34]:
a1[1,1]

0.7564854011693334

In [36]:
a1[1][1]

0.7564854011693334

In [38]:
a1[0:2, 0:2]

array([[0.52063196, 0.13677528],
       [0.65082356, 0.7564854 ]])

In [40]:
a1[[0,1],0:2]

array([[0.52063196, 0.13677528],
       [0.65082356, 0.7564854 ]])

In [41]:
a1[1:3,3]

array([0.09710427, 0.82323889])

In [45]:
m1= np.random.randint(1,3,(3,3))

In [46]:
m1

array([[2, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [47]:
m2 = np.random.randint(2,4,(3,3))

In [48]:
m2

array([[2, 3, 3],
       [3, 3, 3],
       [2, 3, 3]])

In [49]:
m1 * m2

array([[4, 3, 6],
       [6, 3, 3],
       [4, 6, 3]])

In [51]:
m1@m2 # matrix multiplictaion -->@

array([[11, 15, 15],
       [ 9, 12, 12],
       [12, 15, 15]])

In [52]:
pow(m1,3)

array([[8, 1, 8],
       [8, 1, 1],
       [8, 8, 1]])

In [53]:
np.sqrt(m1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [54]:
np.log10(m1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [55]:
np.exp(m1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [56]:
m1**2

array([[4, 1, 4],
       [4, 1, 1],
       [4, 4, 1]])